version: '3.8'
services:
  # ui:
  #   image: ui
  #   environment:
  #     - apiPath=http://api:3333
  #   ports:
  #     - 4200:4200
  api:
    image: api
    ports:
      - 3333:3333
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DATABASE=test
  postgresql:
    image: postgres
    container_name: pg-docker
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DATABASE=test
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ~/postgresql/data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
