version: '3.8'
services:
  api:
    image: api
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=postgres://test:test@postgresql:5432/test
  postgresql:
    image: postgres
    container_name: pg-docker
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DATABASE=test
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ~/postgresql/data:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
